### ISSUE TITLE
Optimisation advice for challengers

### ISSUE THREAD

**Issue by cagataycali** [SelmanKahya/intelligent-flappy#1]
The brains of birds transferred to the next generation are randomly selected. A selection from the brains of the birds that died last in the last generation will provide an effective contribution to the new generation.

https://github.com/SelmanKahya/intelligent-flappy/blob/master/src/game.js#L56

**Comment by SelmanKahya** [comment]
so there is this loop:
https://github.com/SelmanKahya/intelligent-flappy/blob/master/src/game.js#L108

that we copied from here: 
https://github.com/CodingTrain/Toy-Neural-Network-JS/blob/master/examples/neuroevolution-flappybird/ga.js#L65

and it claims that it is an algorithm for picking one bird from an array based on the fitness. so it should not be random, but I bet there are much more effective ways of achieving what we want here.
